;this file for FamiTone2 library generated by text2data tool

soundtrack_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; chill (23)

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $70 ;instrument $01
	.word @env2,@env6,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env5,@env0,@env3
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c2,$c3,$c5,$c7,$cb,$cd,$cb,$c7,$c5,$c3,$c2,$03,$c2,$00,$09
@env2:
	.byte $c8,$cc,$cd,$02,$cc,$cb,$ca,$c9,$00,$07
@env3:
	.byte $cf,$00,$00
@env4:
	.byte $cf,$cf,$ce,$cd,$ca,$c6,$c3,$c0,$00,$07
@env5:
	.byte $cc,$03,$cb,$cb,$ca,$c9,$c7,$c5,$c2,$c0,$00,$09
@env6:
	.byte $b4,$c0,$00,$01


; chill (23)
@song0ch0:
	.byte $fb,$04
@song0ch0loop:
@ref0:
	.byte $80,$4e,$a5,$48,$ad,$52,$ad,$44,$ad
@ref1:
	.byte $4e,$a5,$48,$ad,$52,$ad,$44,$ad
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref1
	.byte $fd
	.word @song0ch0loop

; chill (23)
@song0ch1:
@song0ch1loop:
@ref6:
	.byte $00,$f9,$bb
@ref7:
	.byte $00,$f9,$bb
@ref8:
	.byte $8f,$82,$44,$8d,$3a,$95,$3e,$8d,$36,$95,$48,$8d,$3e,$95,$3a,$8d
	.byte $3e,$95,$3a,$85
@ref9:
	.byte $87,$3e,$95,$44,$8d,$3e,$95,$44,$8d,$3a,$95,$48,$8d,$3a,$95,$36
	.byte $8d,$3e,$8d
@ref10:
	.byte $8f,$44,$8d,$3a,$95,$3e,$8d,$36,$95,$48,$8d,$3e,$95,$3a,$8d,$3e
	.byte $95,$3a,$85
	.byte $ff,$13
	.word @ref9
	.byte $fd
	.word @song0ch1loop

; chill (23)
@song0ch2:
@song0ch2loop:
@ref12:
	.byte $84,$3a,$85,$40,$85,$48,$85,$4e,$85,$56,$85,$40,$85,$3a,$85,$40
	.byte $85,$48,$85,$4e,$85,$56,$85,$40,$85,$3a,$85,$40,$85,$48,$85,$4e
	.byte $85,$56,$85,$40,$85,$3a,$85,$40,$85,$48,$85,$4e,$85,$56,$85
@ref13:
	.byte $3a,$85,$40,$85,$48,$85,$4e,$85,$56,$85,$40,$85,$3a,$85,$40,$85
	.byte $48,$85,$4e,$85,$56,$85,$40,$85,$3a,$85,$40,$85,$48,$85,$4e,$85
	.byte $56,$85,$40,$85,$3a,$85,$40,$85,$48,$85,$4e,$85,$56,$85
	.byte $ff,$2e
	.word @ref13
	.byte $ff,$2e
	.word @ref13
	.byte $ff,$2e
	.word @ref13
	.byte $ff,$2e
	.word @ref13
	.byte $fd
	.word @song0ch2loop

; chill (23)
@song0ch3:
@song0ch3loop:
@ref18:
	.byte $88,$0a,$8d,$86,$02,$8d,$02,$85,$88,$0a,$85,$86,$02,$8d,$02,$8d
	.byte $02,$85,$88,$0a,$85,$86,$02,$8d,$02,$8d,$02,$85,$88,$0a,$85,$86
	.byte $02,$8d,$02,$8d,$02,$85
@ref19:
	.byte $88,$0a,$85,$86,$02,$8d,$02,$8d,$88,$0a,$8d,$86,$02,$8d,$02,$8d
	.byte $88,$0a,$8d,$86,$02,$8d,$02,$8d,$88,$0a,$8d,$86,$02,$8d,$02,$8d
	.byte $ff,$1e
	.word @ref18
	.byte $ff,$18
	.word @ref19
	.byte $ff,$1e
	.word @ref18
	.byte $ff,$18
	.word @ref19
	.byte $fd
	.word @song0ch3loop

; chill (23)
@song0ch4:
@song0ch4loop:
@ref24:
	.byte $f9,$bd
@ref25:
	.byte $f9,$bd
@ref26:
	.byte $f9,$bd
@ref27:
	.byte $f9,$bd
@ref28:
	.byte $f9,$bd
@ref29:
	.byte $f9,$bd
	.byte $fd
	.word @song0ch4loop
